spring:
  zipkin:
    base-url: http://localhost:9411  # 日志跟踪收集服务地址
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      server:
        git:
          uri: https://github.com/langjuxu/spring-clound-q/spring-clound-config-server
  #配置文件所在的目录
  cloud:
    config:
      server:
        git:
          search-paths: /**
  #配置文件所在的分支
  cloud:
    config:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9110/eureka/   # 服务注册中心地址
  instance:
    prefer-ip-address: true  # 使用服务注册中心ip地址